# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_querypattern_querypatterntweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncActionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('OK', 'Ok'), ('FAILED', 'Failed')], default='PENDING', max_length=7)),
                ('message_type', models.CharField(choices=[('ERROR', 'Error'), ('INFO', 'Info')], default='ERROR', max_length=7)),
                ('message', models.TextField(blank=True, null=True)),
                ('error_traceback', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
