# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_asyncactionreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=175),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='location',
            field=models.CharField(max_length=160),
        ),
    ]
