# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_auto_20170924_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querypattern',
            name='search_query',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
