# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_auto_20170924_1705'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='querypatterntweet',
            unique_together=set([('query_pattern', 'tweet')]),
        ),
    ]
